"""
Central path configuration. Everything is relative to the project root,
so this works the same on Windows, Mac, or Linux as long as you keep the
folder structure below.

Expected layout (you provide `archive/`, everything else is generated):

    project-root/
    ├── archive/
    │   ├── styles.csv
    │   └── images/
    │       ├── 1163.jpg
    │       └── ...
    ├── data/            <- generated by prepare_data.py / extract_features.py
    ├── models/           <- generated by train_classifiers.py / build_index.py
    ├── app/main.py
    ├── static/index.html
    └── *.py

If your dataset lives somewhere else, set the DATASET_DIR environment
variable to its path instead of moving files around, e.g. (Windows
PowerShell):
    $env:DATASET_DIR = "C:\\Users\\gagan\\Downloads\\archive"
"""
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parent

RAW_DIR = Path(os.environ.get("DATASET_DIR", ROOT / "archive"))
CSV_PATH = RAW_DIR / "styles.csv"
IMG_DIR = RAW_DIR / "images"

DATA_DIR = ROOT / "data"
MODELS_DIR = ROOT / "models"
STATIC_DIR = ROOT / "static"

DATA_DIR.mkdir(exist_ok=True)
MODELS_DIR.mkdir(exist_ok=True)
